name: Training feedback CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # This will create docker image as well
  java_template:
    uses: cyberrangecz/actions-templates/.github/workflows/java_template.yml@master
    secrets:
      READ_PACKAGES: ${{ secrets.READ_PACKAGES }}
    with:
      MAVEN_CLI_OPTS: "-s etc/ci_settings.xml"
      IMAGE_NAME: "training-feedback"
      VERSION_PATH: "etc/ci_settings.xml"

  create_tag:
    uses: cyberrangecz/actions-templates/.github/workflows/tag_template.yml@master
    with:
      VERSION: ${{ vars.VERSION }}
