name: Training feedback CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      confirm_action:
        description: "Type 'yes' if you want to publish and create a new tag"
        required: true
        default: "no"

jobs:
  # This will create docker image as well
  java_template:
    uses: cyberrangecz/actions-templates/.github/workflows/java_template.yml@master
    secrets:
      NVD_API: ${{ secrets.NVD_API }}
    with:
      MAVEN_CLI_OPTS: ""
      IMAGE_NAME: "training-feedback"
      VERSION_PATH: "pom.xml"
